name: CI

on:
  push:
    branches: main
    paths: "lab03/**"

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
        
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: repository checkout
        uses: actions/checkout@v4
      - 
        name: push_me_and_then_just_touch_me
        uses: docker/build-push-action@v5
        with:
          context: "./lab03"
          push: true
          tags: vladkilinich/lab03:latest
